### ISSUE TITLE
xunitmerge gives a TypeError with Python 3.6

### ISSUE THREAD

**Issue by sshazlijnj** [miki725/xunitmerge#8]
I am getting a TypeError when using xunitmerge with Python 3.6 on Ubuntu 18.04. Here is the Traceback
Traceback (most recent call last):
  File "/usr/local/bin/xunitmerge", line 26, in <module>
    merge_xunit(args.report, args.output)
  File "/usr/local/lib/python3.6/dist-packages/xunitmerge/xmerge.py", line 130, in merge_xunit
    merged.write(output, encoding='utf-8', xml_declaration=True)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 776, in write
    short_empty_elements=short_empty_elements)
  File "/usr/local/lib/python3.6/dist-packages/xunitmerge/xmerge.py", line 70, in _serialize_xml
    original_serialize(write, elem, *args, **kwargs)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 941, in _serialize_xml
    short_empty_elements=short_empty_elements)
  File "/usr/local/lib/python3.6/dist-packages/xunitmerge/xmerge.py", line 70, in _serialize_xml
    original_serialize(write, elem, *args, **kwargs)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 941, in _serialize_xml
    short_empty_elements=short_empty_elements)
  File "/usr/local/lib/python3.6/dist-packages/xunitmerge/xmerge.py", line 70, in _serialize_xml
    original_serialize(write, elem, *args, **kwargs)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 941, in _serialize_xml
    short_empty_elements=short_empty_elements)
  File "/usr/local/lib/python3.6/dist-packages/xunitmerge/xmerge.py", line 68, in _serialize_xml
    ).encode('utf-8'))
TypeError: write() argument must be str, not bytes

**Comment by srids** [comment]
same here - any resolution please. in my case, i have 2 junit xml reports being generated by pytest and when trying to merge, i get this same issue.

**Comment by lbnshrivas** [comment]
@miki725 can you folks please merge the above PR Fix type error issue in Python 3 #9 as we are also hitting the same issue.

**Comment by Chris2048** [comment]
Hi, will there be a new release including this fix? Regards.
